#!/bin/bash
set -e

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

case "$OS" in
    darwin)
        OS="macos"
        ;;
    linux)
        OS="linux"
        ;;
    *)
        echo "Unsupported OS: $OS"
        exit 1
        ;;
esac

case "$ARCH" in
    x86_64|amd64)
        ARCH="x86_64"
        ;;
    arm64|aarch64)
        ARCH="aarch64"
        ;;
    *)
        echo "Unsupported architecture: $ARCH"
        exit 1
        ;;
esac

PLATFORM="${OS}_${ARCH}"
TARGET_FILE="src/bindings/${PLATFORM}.rs"

echo "Generating bindings for $PLATFORM..."

cargo clean
cargo build --features bundled,buildtime_bindgen --lib

BINDGEN_FILE=$(find target/debug/build/zenroom-*/out/bindings.rs 2>/dev/null | head -n1)

if [ -z "$BINDGEN_FILE" ]; then
    echo "Error: Could not find generated bindings"
    exit 1
fi

BINDGEN_VERSION=$(cargo tree --depth 0 -i bindgen 2>/dev/null | grep bindgen | awk '{print $2}' || echo "unknown")

cat > "$TARGET_FILE" << EOF
// Pre-generated FFI bindings for $OS $ARCH
// Generated by bindgen $BINDGEN_VERSION from zenroom.h

$(cat "$BINDGEN_FILE")
EOF

echo "Bindings written to $TARGET_FILE"
