#!/bin/sh


verbose=1

alias zenroom="$1"

# generated by aesgcm test to be run first
# scenario="Alice generate a keypair"
# scenario="Alice publishes her public key"
# scenario="Bob generate a keypair"
# scenario="Bob publishes his public key"

scenario="Alice signs a message for Bob"
echo $scenario
cat <<EOF | zenroom -z -d$verbose -k alice.keys | tee alice_signs_to_bob.json
Scenario 'simple': $scenario
Given that I am known as 'Alice'
and I have my 'keypair'
When I draft the string 'This is my signed message to Bob'
and I sign the draft as 'signed message'
Then print my 'signed message'
EOF

scenario="Bob verifies the signature from Alice"
echo $scenario
cat <<EOF | zenroom -z -d$verbose -k alice.pub -a alice_signs_to_bob.json
Scenario 'simple': $scenario
Given that I am known as 'Bob'
and I have inside 'Alice' a valid 'public key'
and I have a draft inside 'Alice'
and I have a valid 'signed message'
When I verify the 'signed message' is authentic
Then print 'signature' 'correct'
and print as 'string' the 'text' inside 'signed message'
EOF
