print("== SECRET SHARING test")
rng = RNG.new()
msg = rng:oct(64)
-- print("message: ")
s1,s2,s3,s4,s5 = SSS.share(msg,5,3)
-- print(s1)
-- print(s2)
-- print(s3)
-- print(s4)
-- print(s5)
sc = SSS.combine(s1..s2..s3,3)
-- print(sc)
assert(sc == msg)
print ("OK")
