/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dyne_zenroom_Zencode */

#ifndef _Included_dyne_zenroom_Zencode
#define _Included_dyne_zenroom_Zencode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dyne_zenroom_Zencode
 * Method:    zenroom
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dyne_zenroom_Zencode_zenroom
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
