load ../bats_setup
load ../bats_zencode
SUBDOC=bbs

@test "Create the sha proof of some messages" {
    cat << EOF | save_asset proof_data.json
{
	"bbs_messages": [
		"above 18",
		"italian",
		"professor"
	],
	"bbs_disclosed_indexes": [
		1,
		3
	]
}
EOF
    cat <<EOF | zexe create_proof.zen proof_data.json
Scenario bbs
# Given I have a 'bbs public key' inside 'The Authority'
# Given I have a 'bbs credential'
Given I have a 'string array' named 'bbs messages'
Given I have a 'number array' named 'bbs disclosed indexes'
When I create the bbs key
and I create the bbs public key
When I create the random object of '256' bits 
When I rename the 'random_object' to 'bbs presentation header'
When I create the bbs signature of 'bbs messages'
and I rename 'bbs signature' to 'bbs credential'
When I create the bbs disclosed messages
When I create the bbs proof
Then print the 'bbs proof'
Then print the 'bbs public key'
Then print the 'bbs disclosed messages'
Then print the 'bbs disclosed indexes'
Then print the 'bbs presentation header'
Then print the 'bbs credential'
EOF
    save_output verify_proof_data.json
#    assert_output ''
}

@test "Verify the sha proof of some messages" {

    cat <<EOF | zexe verify_proof.zen verify_proof_data.json
Scenario bbs
Given I have a 'bbs public key'
and I have a 'bbs proof'
and I have a 'base64' named 'bbs presentation header'
and I have a 'number array' named 'bbs disclosed indexes'
and I have a 'string array' named 'bbs disclosed messages'
When I verify the bbs proof
Then print the string  'bbs zkp verification successful'
EOF
    save_output verify_proof_bbs.json
    assert_output '{"output":["bbs_zkp_verification_successful"]}'
}

@test "Create sha proof of some messages (explicit statement)" {
    cat << EOF | save_asset proof2_data.json
{
	"bbs_messages": [
		"above 18",
		"italian",
		"professor"
	],
	"bbs_disclosed_indexes": [
		1,
		3
	]
}
EOF
    cat <<EOF | zexe create_proof2.zen proof2_data.json
Scenario bbs
Given I have a 'string array' named 'bbs messages'
Given I have a 'number array' named 'bbs disclosed indexes'
When I create the bbs key
and I create the bbs public key
When I create the bbs signature of 'bbs messages'
and I rename 'bbs signature' to 'bbs credential'
When I create the random object of '256' bits 
When I rename the 'random_object' to 'bbs presentation header'
When I create the bbs disclosed messages
When I create the bbs proof of the signature 'bbs credential' of the messages 'bbs messages' with public key 'bbs public key' presentation header 'bbs presentation header' and disclosed indexes 'bbs disclosed indexes'
Then print the 'bbs proof'
Then print the 'bbs public key'
Then print the 'bbs disclosed messages'
Then print the 'bbs disclosed indexes'
Then print the 'bbs presentation header'
Then print the 'bbs credential'
EOF
    save_output verify_proof2_data.json
}

@test "Verify sha proof of some messages (explicit statement)" {

    cat <<EOF | zexe verify_proof2.zen verify_proof2_data.json
Scenario bbs
Given I have a 'bbs public key'
and I have a 'bbs proof'
and I have a 'base64' named 'bbs presentation header'
and I have a 'number array' named 'bbs disclosed indexes'
and I have a 'string array' named 'bbs disclosed messages'
When I verify the bbs proof with public key 'bbs public key' presentation header 'bbs presentation header' disclosed messages 'bbs disclosed messages' and disclosed indexes 'bbs disclosed indexes'
Then print the string  'bbs zkp verification successful'
EOF
    save_output verify_proof2_bbs.json
    assert_output '{"output":["bbs_zkp_verification_successful"]}'
}

@test "DOCS: create issuer keys" {
    cat <<EOF | zexe issuer_keys_docs.zen
Scenario 'bbs': authority generates its keys
Given I am 'The Authority'
When I create the bbs key
When I create the bbs public key
Then print my 'bbs public key'
Then print my 'keyring'
EOF
    save_output issuer_keys_output_docs.json
}

@test "DOCS: create credential example" {
    cat << EOF | save_asset data_credential_docs.json
{
    "The_Authority": {
        "bbs_public_key": "i33+cqmLXaneXsvmCv9EE+4GU1+cxO8uZYV+wTLjU0UL7uXbsBW2D0Pd34j5I2E6BFxcFdaVfACQutLX3kQ1TaO0V9Iz1KTn03/OHzyNKhWBkXEYolZ6mdc75DZQDy1k",
        "keyring": {
            "bbs": "EIRxtRfx2zDcSEogGyVJ29yj4wHwncuNQMrCpLnfknA="
        }
    },
    "bbs_messages": [
		"above 18",
		"italian",
		"professor"
	]
}
EOF
    cat <<EOF | zexe create_credential_docs.zen data_credential_docs.json
Scenario 'bbs': authority generates the private credential

Given I am 'The Authority'
and I have my 'keyring'

Given I have a 'string array' named 'bbs messages'

# The hash function used to generate the signature, to create the proof and to verify it   
# must be the same in all the three cases.

# The private credential is generated by signing the messages.
When I create the bbs signature of 'bbs messages'
When I rename the 'bbs signature' to 'bbs credential'

Then print the 'bbs messages'
Then print the 'bbs credential'
EOF
    save_output output_credential_docs.json

}

@test "DOCS: create proof example" {
    cat << EOF | save_asset proof_data_docs.json
{
	"The_Authority": {
        "bbs_public_key": "i33+cqmLXaneXsvmCv9EE+4GU1+cxO8uZYV+wTLjU0UL7uXbsBW2D0Pd34j5I2E6BFxcFdaVfACQutLX3kQ1TaO0V9Iz1KTn03/OHzyNKhWBkXEYolZ6mdc75DZQDy1k"
	},
    "bbs_credential": "oamUr6F4m2WuHNhn2zah0TCy/oBb2r09ozWn/bmzvv/KMaBcN0tTySjJCESBUXi8M050WIdBiYg6pxd87UQeBVgfNKK39OGNlnZM2GNZFfE=",
	"bbs_messages": [
		"above 18",
		"italian",
		"professor"
	],
	"bbs_disclosed_indexes": [
		1,
		3
	]
}
EOF
    cat <<EOF | zexe create_proof_docs.zen proof_data_docs.json
Scenario 'bbs': participant generates the bbs proof

Given I have a 'bbs public key' inside 'The Authority'
Given I have a 'bbs credential'
Given I have a 'string array' named 'bbs messages'
# This is the same hash function used by the Authority to sign the messages.

Given I have a 'number array' named 'bbs disclosed indexes'

When I create the random object of '256' bits 
When I rename the 'random_object' to 'bbs presentation header'

When I create the bbs disclosed messages

# The SAME hash function must be used in BOTH the creation and the verification. 
When I create the bbs proof of the signature 'bbs credential' of the messages 'bbs messages' with public key 'bbs public key' presentation header 'bbs presentation header' and disclosed indexes 'bbs disclosed indexes'
When I rename the 'bbs proof' to 'bbs proof verbose'
When I create the bbs proof

Then print the 'bbs proof verbose'
Then print the 'bbs proof'
Then print the 'bbs public key'
Then print the 'bbs disclosed messages'
Then print the 'bbs disclosed indexes'
Then print the 'bbs presentation header'
Then print the 'bbs credential'
EOF
    save_output created_proof_docs.json
}


@test "DOCS: verify proof example" {
    cat <<EOF | zexe verify_proof_docs.zen created_proof_docs.json
Scenario bbs: verify a bbs proof

# We load al the necessary objects one at a time
Given I have a 'bbs public key'
and I have a 'bbs proof'
and I have a 'base64' named 'bbs presentation header'
Given I have a 'number array' named 'bbs disclosed indexes'
and I have a 'string array' named 'bbs disclosed messages'

# The SAME hash function must be used in BOTH the creation and the verification.
When I verify the bbs proof with public key 'bbs public key' presentation header 'bbs presentation header' disclosed messages 'bbs disclosed messages' and disclosed indexes 'bbs disclosed indexes'
When I verify the bbs proof

# The print is executed only if the verification was successful
Then print the string  'bbs zkp verification successful'
EOF
    save_output verified_proof_docs.json
}
