/* This file is part of Zenroom (https://zenroom.dyne.org)
 *
 * Copyright (C) 2026 Dyne.org foundation
 * designed, written and maintained by Denis Roio <jaromil@dyne.org>
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

#include "src/encoding.h"
#include "src/challenge_schedule.h"
#include "src/hash.h"
#include "src/npro.h"

#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define VECTOR_PATH "../../test/vectors/niwi/primitive-vectors.txt"

typedef struct {
    uint64_t state;
} NiwiTestRng;

static void niwi_test_rng_init(NiwiTestRng *rng, uint64_t seed) {
    rng->state = seed ? seed : UINT64_C(0x6e697769);
}

static uint64_t niwi_test_rng_next(NiwiTestRng *rng) {
    uint64_t x = rng->state;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    rng->state = x;
    return x * UINT64_C(2685821657736338717);
}

static void niwi_test_rng_bytes(NiwiTestRng *rng, uint8_t *out, size_t len) {
    for (size_t i = 0; i < len; i++) {
        if ((i & 7u) == 0u) {
            uint64_t x = niwi_test_rng_next(rng);
            for (size_t j = 0; j < 8 && i + j < len; j++)
                out[i + j] = (uint8_t)(x >> (j * 8));
        }
    }
}

static void hex_append(char *out, size_t out_cap, size_t *off,
                       const uint8_t *data, size_t len) {
    static const char hex[] = "0123456789abcdef";
    for (size_t i = 0; i < len; i++) {
        assert(*off + 2 < out_cap);
        out[(*off)++] = hex[data[i] >> 4];
        out[(*off)++] = hex[data[i] & 0x0f];
    }
}

static void line_append(char *out, size_t out_cap, size_t *off,
                        const char *name, const uint8_t *data, size_t len) {
    int n = snprintf(out + *off, out_cap - *off, "%s=", name);
    assert(n > 0);
    *off += (size_t)n;
    hex_append(out, out_cap, off, data, len);
    assert(*off + 1 < out_cap);
    out[(*off)++] = '\n';
    out[*off] = '\0';
}

static void text_append(char *out, size_t out_cap, size_t *off,
                        const char *text) {
    size_t len = strlen(text);
    assert(*off + len < out_cap);
    memcpy(out + *off, text, len);
    *off += len;
    out[*off] = '\0';
}

static size_t generate_vectors(char *out, size_t out_cap) {
    size_t off = 0;
    uint8_t buf[512];
    uint8_t digest[32];
    NiwiTestRng rng;

    text_append(out, out_cap, &off, "# NIWI primitive vectors v1\n");
    text_append(out, out_cap, &off, "# Generated by lib/blindzap/tests/test_vectors.c\n");
    text_append(out, out_cap, &off, "protocol=niwi-v1\n");

    size_t n = niwi_encode_bytes((const uint8_t *)"niwi", 4, buf, sizeof(buf));
    assert(n == 8);
    line_append(out, out_cap, &off, "encoding.bytes.niwi", buf, n);

    n = niwi_encode_protocol_version(1, 0, buf, sizeof(buf));
    assert(n == 4);
    line_append(out, out_cap, &off, "encoding.protocol.1_0", buf, n);

    n = niwi_encode_tagged("VEC1", (const uint8_t *)"payload", 7, buf, sizeof(buf));
    assert(n == 15);
    line_append(out, out_cap, &off, "encoding.tagged.vec1", buf, n);

    niwi_hash_one_shot(NIWI_TAG_PROTO, (const uint8_t *)"primitive-vectors", 17,
                       digest);
    line_append(out, out_cap, &off, "hash.proto.primitive_vectors", digest, 32);

    niwi_hash_one_shot(NIWI_TAG_STMT, (const uint8_t *)"primitive-vectors", 17,
                       digest);
    line_append(out, out_cap, &off, "hash.stmt.primitive_vectors", digest, 32);

    niwi_npro_t *npro = niwi_npro_create(1);
    assert(npro != NULL);
    assert(niwi_npro_query(npro, "NV01", (const uint8_t *)"alpha", 5, digest) == 0);
    line_append(out, out_cap, &off, "npro.nv01.alpha", digest, 32);
    assert(niwi_npro_query(npro, "NV01", (const uint8_t *)"beta", 4, digest) == 0);
    line_append(out, out_cap, &off, "npro.nv01.beta", digest, 32);
    niwi_npro_set_cutoff(npro);
    size_t gamma_len = niwi_npro_gamma_size(npro);
    assert(gamma_len > 0 && gamma_len < sizeof(buf));
    assert(niwi_npro_serialize_gamma(npro, buf, sizeof(buf)) == gamma_len);
    line_append(out, out_cap, &off, "npro.gamma.two_queries", buf, gamma_len);
    niwi_npro_free(npro);

    niwi_test_rng_init(&rng, UINT64_C(0x4e49574900000001));
    uint8_t opening[64];
    memset(opening, 0, sizeof(opening));
    memcpy(opening, "challenge-share", 15);
    niwi_test_rng_bytes(&rng, opening + 32, 32);
    niwi_hash_one_shot(NIWI_TAG_KCS, opening, sizeof(opening), digest);
    line_append(out, out_cap, &off, "commitment.klp22.fixed_opening", digest, 32);
    line_append(out, out_cap, &off, "commitment.klp22.opening", opening, sizeof(opening));

    memset(opening, 0, sizeof(opening));
    memcpy(opening, "leaf-column-0", 13);
    niwi_test_rng_bytes(&rng, opening + 32, 32);
    niwi_hash_one_shot(NIWI_TAG_LEAF, opening, sizeof(opening), digest);
    line_append(out, out_cap, &off, "commitment.leaf.fixed_preimage", digest, 32);
    line_append(out, out_cap, &off, "commitment.leaf.preimage", opening, sizeof(opening));

    niwi_challenge_schedule_t schedule;
    uint8_t commitment[32], circuit[32], statement[32], root[32], response[32];
    for (size_t i = 0; i < 32; i++) {
        commitment[i] = (uint8_t)(0x10 + i);
        circuit[i] = (uint8_t)(0x20 + i);
        statement[i] = (uint8_t)(0x30 + i);
        root[i] = (uint8_t)(0x40 + i);
        response[i] = (uint8_t)(0x50 + i);
    }
    assert(niwi_schedule_init(&schedule, 1, 0, 0) == 0);
    assert(niwi_schedule_bind_share_commitment(&schedule, commitment) == 0);
    assert(niwi_schedule_bind_statement(&schedule, circuit, statement, root) == 0);
    assert(niwi_schedule_derive_challenge1(&schedule, digest) == 0);
    line_append(out, out_cap, &off, "schedule.challenge1", digest, 32);
    assert(niwi_schedule_open_share(&schedule, opening) == 0);
    assert(niwi_schedule_bind_response(&schedule, response) == 0);
    assert(niwi_schedule_derive_challenge2(&schedule, digest) == 0);
    line_append(out, out_cap, &off, "schedule.challenge2", digest, 32);

    return off;
}

static void write_vectors(void) {
    char generated[8192];
    size_t len = generate_vectors(generated, sizeof(generated));
    FILE *f = fopen(VECTOR_PATH, "wb");
    assert(f != NULL);
    assert(fwrite(generated, 1, len, f) == len);
    assert(fclose(f) == 0);
}

static void check_vectors(void) {
    char generated[8192];
    char committed[8192];
    size_t generated_len = generate_vectors(generated, sizeof(generated));

    FILE *f = fopen(VECTOR_PATH, "rb");
    assert(f != NULL);
    size_t committed_len = fread(committed, 1, sizeof(committed), f);
    assert(ferror(f) == 0);
    assert(fclose(f) == 0);

    assert(generated_len == committed_len);
    assert(memcmp(generated, committed, generated_len) == 0);
}

static void check_mutations_change_vectors(void) {
    uint8_t a[64];
    uint8_t b[64];
    uint8_t da[32];
    uint8_t db[32];
    NiwiTestRng rng_a;
    NiwiTestRng rng_b;

    niwi_test_rng_init(&rng_a, UINT64_C(0x4e49574900000001));
    niwi_test_rng_init(&rng_b, UINT64_C(0x4e49574900000002));
    niwi_test_rng_bytes(&rng_a, a, sizeof(a));
    niwi_test_rng_bytes(&rng_b, b, sizeof(b));
    assert(memcmp(a, b, sizeof(a)) != 0);

    niwi_hash_one_shot(NIWI_TAG_PROTO, (const uint8_t *)"primitive-vectors", 17,
                       da);
    niwi_hash_one_shot(NIWI_TAG_STMT, (const uint8_t *)"primitive-vectors", 17,
                       db);
    assert(memcmp(da, db, sizeof(da)) != 0);

    assert(niwi_encode_protocol_version(1, 0, a, sizeof(a)) == 4);
    assert(niwi_encode_protocol_version(1, 1, b, sizeof(b)) == 4);
    assert(memcmp(a, b, 4) != 0);
}

int main(int argc, char **argv) {
    if (argc == 2 && strcmp(argv[1], "--write") == 0) {
        write_vectors();
        printf("Wrote " VECTOR_PATH "\n");
        return 0;
    }

    check_vectors();
    check_mutations_change_vectors();
    printf("lib/blindzap deterministic vector self-check passed.\n");
    return 0;
}
