/*  Zenroom (DECODE project)
 *
 *  (c) Copyright 2017-2018 Dyne.org foundation
 *  designed, written and maintained by Denis Roio <jaromil@dyne.org>
 *
 * This source code is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Public License as published
 * by the Free Software Foundation; either version 3 of the License,
 * or (at your option) any later version.
 *
 * This source code is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * Please refer to the GNU Public License for more details.
 *
 * You should have received a copy of the GNU Public License along with
 * this source code; if not, write to:
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <stdio.h>
#include <errno.h>
#include <jutils.h>
#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>
#include <luazen.h>
#include <lua_functions.h>

#include <crypto.h>
#include <zenroom.h>

#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif

extern int lualibs_load_all_detected(lua_State *L);
extern int lua_cjson_safe_new(lua_State *l);
extern int lua_cjson_new(lua_State *l);
extern void zen_add_io(lua_State *L);
extern zen_extension_t zen_extensions[];

luaL_Reg lualibs[] = {
	{LUA_LOADLIBNAME, luaopen_package},
	{LUA_COLIBNAME,   luaopen_coroutine},
	{LUA_TABLIBNAME,  luaopen_table},
	{LUA_IOLIBNAME,   luaopen_io},
	{LUA_OSLIBNAME,   luaopen_os},
	{LUA_STRLIBNAME,  luaopen_string},
	{LUA_MATHLIBNAME, luaopen_math},
	{LUA_UTF8LIBNAME, luaopen_utf8},
	{LUA_DBLIBNAME,   luaopen_debug},
#if defined(LUA_COMPAT_BITLIB)
	{LUA_BITLIBNAME,  luaopen_bit32},
#endif
	{NULL, NULL}
};


int zen_load_string(lua_State *L, const char *code,
                     size_t size, const char *name) {
	int res;
	res = luaL_loadbufferx(L,code,size,name,"b");
	switch (res) {
	case LUA_OK: { func("loaded %s",name); break; }
	case LUA_ERRSYNTAX: { error("syntax error: %s",name); break; }
	case LUA_ERRMEM: { error("out of memory: %s", name); break;	}
	case LUA_ERRGCMM: {
		error("garbage collection error while loading %s", name);
		break; }
	}
	return(res);
}

int zen_require(lua_State *L) {
	size_t len;
	const char *s = lua_tolstring(L, 1, &len);
	if(!s) return 0;
	// require classic lua libs
	for (luaL_Reg *p = lualibs;
	     p->name != NULL; ++p) {
		if (strcmp(p->name, s) == 0) {
			luaL_requiref(L, p->name, p->func, 1);
			return 1;
		}
	}

	// require our own lua extensions (generated by embed-lua)
	for (zen_extension_t *p = zen_extensions;
	     p->name != NULL; ++p) {
		if (strcmp(p->name, s) == 0) {
			if(zen_load_string(L, p->code, *p->size, p->name)
			   ==LUA_OK) {
				lua_call(L,0,1);
				return 1;
			}
		}
	}

	// require our own C to lua extensions
	if     (strcmp(s, "crypto")==0) {
		luaL_requiref(L, s, luaopen_crypto, 1); return 1; }
	else if(strcmp(s, "json")  ==0) {
		luaL_requiref(L, s, lua_cjson_safe_new, 1);	return 1; }
	else if(strcmp(s, "cjson_full") ==0) {
		luaL_requiref(L, s, lua_cjson_new, 1); return 1; }
	else {
		// shall we bail out and abort execution here?
		warning("required extension not found: %s",s);
		return 1; }

	return 0;
}

int zen_require_override(lua_State *L) {
	static const struct luaL_Reg custom_require [] =
		{ {"require", zen_require}, {NULL, NULL} };
	lua_getglobal(L, "_G");
	luaL_setfuncs(L, custom_require, 0);
	lua_pop(L, 1);
	return 1;
}

void zen_load_extensions(lsb_lua_sandbox *lsb) {
	act("loading language extensions");

	// register our own print and io.write
	zen_add_io(lsb->lua);

	zen_require_override(lsb->lua);

	// just the constructors are enough for cjson
	// zen_add_function(lsb, lua_cjson_safe_new, "cjson");
	// zen_add_function(lsb, lua_cjson_new, "cjson_full");

	// zen_load_cmodule(lsb, (luaL_Reg*) &luazen);

	// load embedded lua extensions generated by build/embed-lualibs

	act("done loading all extensions");

}
