// This file is generated by running build/embed-lualibs
#include <jutils.h>
#include <luasandbox.h>

#include <lualib_lisp.c>
#include <lualib_inspect.c>
#include <lualib_schema_validation.c>
#include <lualib_statemachine.c>
#include <lualib_debugger.c>
#include <lualib_functional.c>

extern void lsb_load_string(lsb_lua_sandbox *lsb, const char *code,
	                        size_t size, char *name);

int lualibs_detected_load(lsb_lua_sandbox *lsb) {

func("loading lisp");
lsb_load_string(lsb, (const char*)src_lua_lisp_lua,
					 src_lua_lisp_lua_len, "lisp");
func("loading inspect");
lsb_load_string(lsb, (const char*)src_lua_inspect_lua,
					 src_lua_inspect_lua_len, "inspect");
func("loading schema_validation");
lsb_load_string(lsb, (const char*)src_lua_schema_validation_lua,
					 src_lua_schema_validation_lua_len, "schema_validation");
func("loading statemachine");
lsb_load_string(lsb, (const char*)src_lua_statemachine_lua,
					 src_lua_statemachine_lua_len, "statemachine");
func("loading debugger");
lsb_load_string(lsb, (const char*)src_lua_debugger_lua,
					 src_lua_debugger_lua_len, "debugger");
func("loading functional");
lsb_load_string(lsb, (const char*)src_lua_functional_lua,
					 src_lua_functional_lua_len, "functional");
	return(6);
}

