// This file is generated by running build/embed-lualibs
#include <jutils.h>
#include <luasandbox.h>

#include <lualib_fennel.c>
#include <lualib_inspect.c>
#include <lualib_statemachine.c>
#include <lualib_debugger.c>
#include <lualib_schema.c>

extern void lsb_load_string(lsb_lua_sandbox *lsb, const char *code,
	                        size_t size, char *name);

int lualibs_detected_load(lsb_lua_sandbox *lsb) {

func("loading fennel");
lsb_load_string(lsb, (const char*)src_lua_fennel_lua,
					 src_lua_fennel_lua_len, "fennel");
func("loading inspect");
lsb_load_string(lsb, (const char*)src_lua_inspect_lua,
					 src_lua_inspect_lua_len, "inspect");
func("loading statemachine");
lsb_load_string(lsb, (const char*)src_lua_statemachine_lua,
					 src_lua_statemachine_lua_len, "statemachine");
func("loading debugger");
lsb_load_string(lsb, (const char*)src_lua_debugger_lua,
					 src_lua_debugger_lua_len, "debugger");
func("loading schema");
lsb_load_string(lsb, (const char*)src_lua_schema_lua,
					 src_lua_schema_lua_len, "schema");
	return(5);
}

