// Generated by build/codegen_ecp_factory.sh
// Wed 27 May 2020 12:53:40 PM CEST

#ifndef __ZEN_ECP_BLS461_H__

#include <ecp_BLS461.h>
#include <ecp2_BLS461.h>
#include <ecdh_BLS461.h>
#include <pair_BLS461.h>

#define BIGSIZE 384
#include <zen_big_factory.h>
#include <zen_ecp.h>

#define ECP ECP_BLS461
#define ECP2 ECP2_BLS461

#define CURVE_NAME "BLS461"
#define CURVE_A CURVE_A_BLS461
#define CURVE_B Curve_B_BLS461
#define CURVE_B_I CURVE_B_I_BLS461
#define CURVE_Gx CURVE_Gx_BLS461
#define CURVE_Gy CURVE_Gy_BLS461
#define CURVE_Order CURVE_Order_BLS461
#define CURVE_Cofactor CURVE_Cof_BLS461
#define CURVE_G2xa CURVE_Pxa_BLS461
#define CURVE_G2xb CURVE_Pxb_BLS461
#define CURVE_G2ya CURVE_Pya_BLS461
#define CURVE_G2yb CURVE_Pyb_BLS461

#define ECP_copy(d,s) ECP_BLS461_copy(d,s)
#define ECP_set(d,x,y) ECP_BLS461_set(d, x, y)
#define ECP_setx(d,x,n) ECP_BLS461_setx(d, x, n)
#define ECP_affine(d) ECP_BLS461_affine(d)
#define ECP_inf(d) ECP_BLS461_inf(d)
#define ECP_isinf(d) ECP_BLS461_isinf(d)
#define ECP_unity(d) ECP_BLS461_isunity(d)
#define ECP_parity(d) ECP_BLS461_parity(d)
#define ECP_add(d,s) ECP_BLS461_add(d,s)
#define ECP_sub(d,s) ECP_BLS461_sub(d,s)
#define ECP_neg(d) ECP_BLS461_neg(d)
#define ECP_dbl(d) ECP_BLS461_dbl(d)
#define ECP_mul(d,b) ECP_BLS461_mul(d,b)
#define ECP_equals(l,r) ECP_BLS461_equals(l,r)
#define ECP_fromOctet(d,o) ECP_BLS461_fromOctet(d, o)
#define ECP_toOctet(o,d,b) ECP_BLS461_toOctet(o,d,b)
#define ECP_generator(e) ECP_BLS461_generator(e)
#define ECP_mapit(q,w) ECP_BLS461_mapit(q,w)
#define ECP_validate(o) ECP_BLS461_PUBLIC_KEY_VALIDATE(o)

#define FP2 FP2_BLS461
#define FP2_from_BIGs(x,a,b) FP2_BLS461_from_BIGs(x,a,b)

#define ECP2_copy(d,s) ECP2_BLS461_copy(d,s)
#define ECP2_set(d,x,y) ECP2_BLS461_set(d, x, y)
#define ECP2_setx(d,x) ECP2_BLS461_setx(d, x)
#define ECP2_affine(d) ECP2_BLS461_affine(d)
#define ECP2_inf(d) ECP2_BLS461_inf(d)
#define ECP2_isinf(d) ECP2_BLS461_isinf(d)
#define ECP2_add(d,s) ECP2_BLS461_add(d,s)
#define ECP2_sub(d,s) ECP2_BLS461_sub(d,s)
#define ECP2_neg(d) ECP2_BLS461_neg(d)
#define ECP2_dbl(d) ECP2_BLS461_dbl(d)
#define ECP2_mul(d,b) ECP2_BLS461_mul(d,b)
#define ECP2_equals(l,r) ECP2_BLS461_equals(l,r)
#define ECP2_fromOctet(d,o) ECP2_BLS461_fromOctet(d, o)
#define ECP2_toOctet(o,d) ECP2_BLS461_toOctet(o,d)
#define ECP2_generator(e) ECP2_BLS461_generator(e)
#define ECP2_mapit(q,w) ECP2_BLS461_mapit(q,w)

#define PAIR_ate(r,p,q) PAIR_BLS461_ate(r,p,q)
#define PAIR_fexp(x) PAIR_BLS461_fexp(x)
#define PAIR_G2mul(p,b)	PAIR_BLS461_G2mul(p,b)
#define PAIR_G1mul(p,b) PAIR_BLS461_G1mul(p,b)

#endif
